version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: sei_postgres
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha_rede

volumes:
  pgdata:

networks:
  minha_rede:
    driver: bridge
